title = "Anthea Piong"
baseURL = "https://piong.netlify.app"
languageCode = "en-us"

# This is just to get the exampleSite to work with the theme 
# in this repository. Don't mimic this. When using the theme
# you should place it in themes/codex and list theme = "codex"
theme = "codex"


[params]
  # This will show the twitter icon which will link to twitter.com/your-twitter-handle
  # You can omit the @ symbol
  # twitter = "your-twitter-handle"
  # This will show the github icon which will link to github.com/your-github-handle
  # You can omit the @ symbol
  github = "piong"
  linkedin = "piong"


# DONT OVERRIDE #

[[menu.main]]
    identifier = "about"
    name = "about"
    title = "Anthea Piong"
    url = "/"

[[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Blog"
    url = "/blog"

[[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "Resume"
    url = "/resume"


preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #
